name = "heimdall-gatekeeper"
compatibility_date = "2026-04-22"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "heimdall-gatekeeper"
database_id = "85190083-1888-48ba-8af8-00e3d73673f1"
